[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "www_Day_Dream"
name = "BullwormRifleFF"
description = "A Last Train Outta' Wormtown mod that enables friendly fire between pardners!"
websiteUrl = "https://github.com/wwwDayDream/BullwormRifleFF"
containsNsfwContent = false

[package.dependencies]
BepInEx_Wormtown-BepInExPack = "5.4.22"
www_Day_Dream-MultiplayerModRestrictor = "0.3.0"

[build]
icon = "icon.png"
readme = "./TS-README.md"
outdir = "../"

[[build.copy]]
source = "../LICENSE"
target = "/"

[[build.copy]]
source = "../CHANGELOG.md"
target = "/"

[[build.copy]]
source = "../BullwormRifleFF/bin/Release/netstandard2.1/wwwDayDream.BullwormRifleFF.dll"
target = "/BepInEx/plugins/BullwormRifleFF/"

[publish]
communities = [ "last-train-outta-wormtown" ]
categories = [ "mods" ]
