[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = ""
name = ""
description = ""
websiteUrl = ""
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = ""

[build]
icon = "icon.png"
readme = "./TS-README.md"
outdir = "../"

[[build.copy]]
source = "../LICENSE"
target = "/"

[[build.copy]]
source = "../CHANGELOG.md"
target = "/"

[[build.copy]]
source = "../bin/Release//.dll"
target = "/BepInEx/plugins//"

[publish]
communities = [ "" ]
categories = [ "" ]
